#=
Pentagon numbers

Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
=#

#Approach: checking whether a number is a pentagonal number is actually trivial,
#following from the quadratic equation



include("utils/sgon.jl")


s = 5   # find 5-gon (pentagonal) numbers

minpair = nothing
maxn = 10000

diff_init = sgon(s+1,maxn)-sgon(s,maxn)  # high-ball guess. will find minimum less than this initial guess
                                    # note that the differences between triangle numbers grow

diff = diff_init

for n1=1:maxn
 for n2 = n1+1:maxn
  p1 = sgon(s, n1)
  p2 = sgon(s, n2)

  if (is_sgon(p1+p2, s) !=0) & (is_sgon(p2-p1, s) != 0)
   global diff = minimum([diff,p2 - p1])
   println("$p1, $p2, diff = $diff")
  end
 end
end

if diff < diff_init    #some smaller solutions were found
    println( "For the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised... the value of D is: $diff")
end


